### ISSUE TITLE
SHOW STATS only returns results for the first 9 databases

### ISSUE THREAD

**Issue by zygiss** [larseen/pgbouncer_exporter#10]
We have a Postgres server with 75 dabases.  PgBouncer exporter correctly returns  `databases` and `pools` metrics, e.g.
```
user@db:~$ curl -s metrics-interface:3040/metrics | grep -v "^#" | grep -c pgbouncer_databases_max_connections
75
```

However we noticed that we only get the `pgbouncer_stats_` metrics for the first 9 of the databases:
```
user@db:~$ curl -s metrics-interface:3040/metrics | grep -v "^#" | grep -c pgbouncer_stats_total_xact_time
9
```
I'm scaping the exporter directly for the tests above, so our Prometheus scrape or relabeling configuration isn't at play here.

We are also running a build from the latest commit of the exporter.

I fail to see any reasons why we only get stats for 9 DBs from reading the exporter code, AFAICS, it just iterates over the rows returned and prints stats.  I verified that `show stats` as returned by `pgbouncer-admin` return complete stats and went as far as running a packet capture of the traffic between the exporter and PgBouncer to verify stats are returned for all of 75 DBs, they are.  We're not running into any resource limits or timeouts on the node.

Do you have any suggestions for how to debug this further or what I'm overlooking or doing wrong?  At this point I'm thinking this must be something really obvious, but I fail to see it.  Thanks.

**Comment by ferringb** [comment]
@zygiss can you please fix the ticket filing for this?

The problem here is that pgbouncer statistics are internall uint64- so when a statistic crosses 2^63, pgbouncer sends that uint64 value and  lib/pg fails to parse it into an int64.

I'll be submitting a PR that makes this more obvious when it occurs, but from what I can tell this isn't a problem with either the exporter or lib/pg- postgres has no uint64 column type, it just has int64- thus what pgbouncer is returning isn't correct for the protocol.

Quite literally, the row that wasn't returned for this ticket has a total byte count field with a value of ```17606157912109483021```; which is >2^63.  lib/pg can't parse it and has behaviour such that it stops consuming all rows after, and due to a bug in pgbouncer exporter, this error isn't surfaced.

**Comment by zygiss** [comment]
Thanks for the help @ferringb.  Fix tracked upstream in https://github.com/pgbouncer/pgbouncer/issues/350.
